name: ${project.name}
author: Dabo Ross
main: net.daboross.bukkitdev.nobreeding.NoBreeding
version: ${project.version}
description: Allows disabling of breeding
commands:
  nobreed:
    description: enable/disable NoBreeding
    usage: |
      To View: /<command>
      To Enable: /<command> enable
      To Disable: /<command> disable
    permission: nobreeding.admin
    permission-message: You do not have permission to use /nobreed. You need the nobreeding.admin permission to use this command.
